In [1]:
import pandas as pd
from textblob import TextBlob

In [2]:
df = pd.read_csv('cmu_data.csv')

In [3]:
df.head()

,wiki_id,freebase_id,book_title,book_author,publication_date,genre,summary
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16559 entries, 0 to 16558
Data columns (total 7 columns):
wiki_id             16559 non-null int64
freebase_id         16559 non-null object
book_title          16559 non-null object
book_author         14177 non-null object
publication_date    10949 non-null object
genre               12841 non-null object
summary             16559 non-null object
dtypes: int64(1), object(6)
memory usage: 905.7+ KB

In [5]:
np_list = []
adj_list = []
advb_list = []

In [6]:
np_tags = ['NN', 'NNP', 'NNPS', 'NNS', 'PRP', 'PRP$']
adj_tags = ['JJ', 'JJR', 'JJS']
advb_tags = ['RB', 'RBR', 'RBS']

In [7]:
i = 0
for summary in df.summary:
    i+=1
    if i % 100 == 0:
        print(i)
        
    adj = []
    advb = []
    
    b = TextBlob(summary)
    pos_tags = b.tags
    
    for tag in pos_tags:
        if tag[1] in adj_tags:
            adj.append(tag[0])
        elif tag[1] in advb_tags:
            advb.append(tag[0])
            
    np_list.append(list(set(b.noun_phrases)))
    adj_list.append(list(set(adj)))
    advb_list.append(list(set(advb)))

100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16200
16300
16400
16500

In [8]:
assert((len(np_list) == 16559) & (len(adj_list) == 16559) & (len(advb_list) == 16559))

In [11]:
df['noun_phrase'] = np_list
df['adjectives'] = adj_list
df['adverbs'] = advb_list

In [12]:
df.head()

,wiki_id,freebase_id,book_title,book_author,publication_date,genre,summary,noun_phrase,adjectives,adverbs
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca...","[mr pilkington, revolutionary song, dogs chase...","[better, malleable, young, violent, poor, more...","[aside, better, away, more, ideas, formally, L..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan...","[wealthy old woman, young woman, top volume, j...","[favorite, orgiastic, scantily-clad, anxious, ...","[Back, down, now, ago, late, more, accidentall..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...,"[main character, m. michel, tarrou, towards, r...","[townspeople, appropriate, young, unexpected, ...","[away, exhaustively, afterward, however, initi..."
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...,"[own biases, berkeley, empirical thesis, speci...","[specific, miraculous, serious, same, direct, ...","[aside, generally, presumably, prior, First, a..."
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...,"[ship lands, radio communication, pham, recogn...","[imaginative, sleeper, dormant, different, pos...","[Shortly, out, roughly, actually, even, incomp..."

In [13]:
df.to_csv('cmu_data_phrase.csv', index=False)